title: Site Name
order: 9
status: wip
context:
    site_name: Site Name
    site_slogan: Site Slogan
    site_front: /
    site_title: Home Page
variants:
  - name: Department Name
    context:
      site_name: Department of College
      site_slogan: College Name

