title: Vertical Video
hidden: false
order: 3
status: wip
variants:
  - name: default
    label: Portraits Block
    hidden: false
    status: null
    context:
      portrait:
        items:
          - portrait_title: "I WOULDN'T HAVE GOTTEN THAT ANYWHERE ELSE."
            portrait_sub: Rockwell Collins
            portrait_link: ../../video/kelly.mp4
            portrait_srt: ../../video/kelly.vtt
            portrait_poster: ../../video/kelly.png
          - portrait_title: Best Study Spots on Campus
            portrait_sub: Take a Tour
            portrait_link: ../../video/kelly.mp4
            portrait_srt: ../../video/kelly.vtt
            portrait_poster: ../../video/study.png
          - portrait_title: From Hawkeyes to Vikings
            portrait_sub: University of Iowa graduates in MN
            portrait_link: ../../video/kelly.mp4
            portrait_srt: ../../video/kelly.vtt
            portrait_poster: ../../video/vikings.png

  - name: basic
    label: Portraits Block Basic
    hidden: false


