title: Vertical Dots
order: 4
status: wip
hidden: false
context:
    vertical_dots:
      sections:
        - section_title: Undergraduate
          section_id: '#'
        - section_title: Graduate
          section_id: '#'
        - section_title: International
          section_id: '#'
        - section_title: Distance and online
          section_id: '#'
        - section_title: Cost and aid
          section_id: '#'