label: Card Block
status: wip
order: 3
context:
  card:
    items:
      - card_tag: News
        card_title: Dedicated to having an impact on human health
        card_link_title: View Story
        card_link_url: https://uiowa.edu/
        card_image: ../../images/feature1.jpg
        card_text: <p>Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
        card_date: June 14, 1984
        card_author: By Lee Hermiston
        card_type: card--open
      - card_tag: News
        card_title: Swinging for the fences in sports management
        card_link_title: View Story
        card_link_url: https://uiowa.edu/
        card_image: ../../images/feature4.jpg
        card_text: <p>Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.</p>
        card_date: June 14, 1984
        card_author: By Lee Hermiston
        card_type: card--enclosed
      - card_tag: News
        card_title: Turning the tide for sick seals
        card_link_title: View Story
        card_link_url: https://uiowa.edu/
        card_image: ../../images/feature3.jpg
        card_text: <p>As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.</p>
        card_date: June 14, 1984
        card_author: By Sara Epstein Moninger
        card_type: card--open
      - card_tag: News
        card_title: Getting to know Iowa's fall 2018 graduates
        card_link_title: View Story
        card_link_url: https://uiowa.edu/
        card_image: ../../images/feature2.jpg
        card_text: <p>Receiving a diploma signals both an ending and a beginning.</p>
        card_date: June 14, 1984
        card_author: By the Office of Strategic Communication
        card_type: card--enclosed


variants:
  - name: default
    label: Card Block Basic
    status: null
    context:
      block_type: basic

  - name: More
    label: Card Block Advanced
    hidden: true
    context:
      block_type: advanced

  - name: advanced
    label: Card Block Advanced
    hidden: true

  - name: basic
    label: Card Block Simple
    hidden: true

