title: Events Block
order: 3
status: wip
hidden: false
name: Events Block
meta:
  dependencies:
    stylesheets:
      - /components/colors/colors.css
context:
  events:
    items:
      - events_card_tag: Carver-Hawkeye Arena
        events_card_title: College of Liberal Arts and Sciences 9 a.m. Commencement Ceremony
        events_card_link_title: Read Article
        events_card_link_url: https://uiowa.edu/
        events_card_image: '../../assets/images/events-01.jpg'
        events_card_text: Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.
        events_card_date: May 16, 2020, 9:00 AM
      - events_card_tag: Carver-Hawkeye Arena
        events_card_title: College of Engineering 9 a.m. Commencement Ceremony
        events_card_link_title: Read Article
        events_card_link_url: https://uiowa.edu/
        events_card_image: '../../assets/images/events-02.jpg'
        events_card_text: Receiving a diploma signals both an ending and a beginning.
        events_card_date: May 17, 2020, 9:00 AM
      - events_card_tag: Carver-Hawkeye Arena
        events_card_title: College of Education 9 a.m. Commencement Ceremony
        events_card_link_title: Read Article
        events_card_link_url: https://uiowa.edu/
        events_card_image: '../../assets/images/events-03.jpg'
        events_card_text: As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.
        events_card_date: May 18, 2020, 9:00 AM

variants:
  - name: default
    label: Events Block Basic
    status: null
    hidden: false
    context:
      block_type: advanced

  - name: basic
    label: Events Block Simple
    hidden: true
