title: Tabs
hidden: false
order: 30
status: wip
context:
  items:
    - title: Chocolate Chip Cookie
      content: |
        <p>Among the most popular of all cookie types, the chocolate chip cookie's invention was a happy accident. In 1930, Ruth Graves Wakefield, who ran the Toll House Inn in Whitman, Massachusetts, ran out of baker's chocolate and substituted for it with pieces of Nestle's® semi-sweet chocolate. </p>
    - title: Sugar Cookie
      content: |
        <p>The sugar cookie is like the vanilla ice cream of cookies—everyone likes it but few claim it as their favorite. Basic ingredients like sugar, flour, butter, eggs, and vanilla make up this popular cookie type.</p>
    - title: Snickerdoodle Cookies
      content: |
        <p>Although the origin of this beloved cookie is up for debate, there's no doubt it's a favorite during the holidays. Snickerdoodles are a type of drop cookie (any cookie that is formed by dropping spoonfuls of dough directly onto a baking sheet) that is coated in cinnamon and sugar. </p>
    - title: Oatmeal Raisin
      content: |
        <p>A seriously underrated cookie, oatmeal raisin is another type of drop cookie. Its dough is oatmeal based, and contains raisins and brown sugar. They're warm and comforting—a reminder of simpler times and grandma's house.</p>
