title: Hero Block
order: 99
status: wip
hidden: true
context:
  hero_type: video
  hero_content: center
  hero_title: 'See for yourself'
  hero_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/hero-image.jpg
  hero_image_alt: 'View of University of Iowa Campus'
  hero_video: ../../assets/video/home.mp4
  cta:
    items:
      - text: 'Schedule a Visit'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline'
        link: 'https://uiowa.edu/'
      - text: 'Areas of Study'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline'
        link: 'https://uiowa.edu/'
      - text: 'Cost and Aid'
        type: 'bttn bttn--secondary bttn--sans-serif bttn--outline'
        link: 'https://uiowa.edu/'
variants:
  - name: default
    hidden: true
  - name: Hero Video Content Center
    context:
      hero_type: video
      hero_content: center
  - name: Hero Video Content Bottom
    context:
      hero_type: video
      hero_content: bottom
      hero_title: 'Undergraduate Admissions'
  - name: Hero Image Content Center
    context:
      hero_type: image
      hero_content: center
      image_path_1: ../../images/widescreen__384_x_216/bg-image.jpg
      image_path_2: ../../images/widescreen__768_x_432/bg-image.jpg
      image_path_3: ../../images/widescreen__1024_x_576/bg-image.jpg
      image_path_4: ../../images/widescreen__1312_x_738/bg-image.jpg
      image_path_5: ../../images/widescreen__1920_x_1080/bg-image.jpg
      image_path_6: ../../images/widescreen__2592_x_1458/bg-image.jpg
  - name: left
    label: Hero Image Content Bottom Left
    context:
      hero_type: image
      hero_content: bottom
      hero_title: 'Undergraduate Admissions'
      image_path_1: ../../images/widescreen__384_x_216/bg-image.jpg
      image_path_2: ../../images/widescreen__768_x_432/bg-image.jpg
      image_path_3: ../../images/widescreen__1024_x_576/bg-image.jpg
      image_path_4: ../../images/widescreen__1312_x_738/bg-image.jpg
      image_path_5: ../../images/widescreen__1920_x_1080/bg-image.jpg
      image_path_6: ../../images/widescreen__2592_x_1458/bg-image.jpg
  - name: grid
    label: Hero Image Grid
    context:
      hero_type: image
      hero_content: grid
      hero_title: 'Welcome Home'
      grid_title_1: <i class="fas fa-map-marker-alt"></i> Residence Halls
      grid_sub_1: The University of Iowa is home to the best comprehensive medical center in Iowaâ€“and one of the best in the country.
      grid_title_2: <i class="fas fa-map-marker-alt"></i> Office of Admissions
      grid_sub_2: Most college towns are just towns near a college. Not Iowa City. The campus and downtown are woven into each other.
      grid_title_3: <i class="fas fa-map-marker-alt"></i> Pentacrest
      grid_sub_3: Big schools have to be big, right?  Nope. Everything on campus is within walking distance, with free buses to get you there faster.
      grid_title_4: Big ten athletics
      grid_sub_4: Kinnick Stadium, with its 69,000+ seats, is the home of Hawkeye Football. But on gameday, the entire town turns black and gold.
      image_path_1: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg
      image_path_2: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg
      image_path_3: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg
      image_path_4: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg
      image_path_5: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg
      image_path_6: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg



