title: Vertical
order: 4
status: wip
context:
    links_nav:
      title: Main Menu
      title_classes: element-invisible
      links:
      - link_nav_text: Admissions
        link_nav_classes: menuparent
        links:
        - link_nav_text: Undergraduate
          link_nav_url: '#'
        - link_nav_text: Graduate
          link_nav_url: '#'
        - link_nav_text: International
          link_nav_url: '#'
        - link_nav_text: Distance and online
          link_nav_url: '#'
        - link_nav_text: Cost and aid
          link_nav_url: '#'
      - link_nav_text: Academics
        link_nav_classes: menuparent
        links:
        - link_nav_text: Areas of study
          link_nav_url: '#'
        - link_nav_text: Leading programs
          link_nav_url: '#'
        - link_nav_text: Career center
          link_nav_url: '#'
        - link_nav_text: Colleges
          link_nav_url: '#'
      - link_nav_text: Research
        link_nav_classes: menuparent
        links:
        - link_nav_text: Students
          link_nav_url: '#'
        - link_nav_text: Faculty
          link_nav_url: '#'
        - link_nav_text: Areas of excellence
          link_nav_url: '#'
      - link_nav_text: Hawkeye life
        link_nav_classes: menuparent
        links:
        - link_nav_text: Iowa City
          link_nav_url: '#'
        - link_nav_text: Living on campus
          link_nav_url: '#'
        - link_nav_text: Alumni community
          link_nav_url: '#'
      - link_nav_text: News
        link_nav_classes: menuparent
        links:
        - link_nav_text: Events
          link_nav_url: '#'
        - link_nav_text: Media resources
          link_nav_url: '#'
      - link_nav_text: Quick Links
        link_nav_classes: menuparent
        links:
        - link_nav_text: MyUI
          link_nav_url: '#'
        - link_nav_text: Student Health and Wellness
          link_nav_url: '#'
        - link_nav_text: Libraries
          link_nav_url: '#'
        - link_nav_text: Course Catalog
          link_nav_url: '#'
        - link_nav_text: Academic Calendars
          link_nav_url: '#'


variants:
  - name: default
    label: Vertical Links
    hidden: false

  - name: links
    label: Links
    hidden: true

  - name: search
    label: Search
    hidden: true
    context:
      links_nav:
        title: 'Top Searches:'
        title_classes:
        links:
        - link_nav_text: Cost
          link_nav_classes:
        - link_nav_text: Financial Aid
          link_nav_classes:
        - link_nav_text: Registration
          link_nav_classes:
