title: Button (Deprecated)
hidden: true
order: 2
status: wip
collated: true
display:
  width: 100%
context:
  button:
    text: More News
    type: bttn--tertiary bttn--caps
    link: https://www.example.com
    icon: yes
variants:
  - name: Button Gold Bg
    context:
      button:
        text: More News
        type: bttn--primary bttn--caps
        link: https://www.example.com
        icon: yes
  - name: Button Black Bg
    context:
      button:
        text: More News
        type: bttn--secondary bttn--caps
        link: https://www.example.com
        icon: yes
  - name: Button Outline
    hidden: false
    context:
      button:
        text: More News
        type: bttn--outline bttn--tertiary bttn--caps
        icon: yes
  - name: Button Outline Sans-Serif
    notes: This variation is used for Card Link component
    hidden: false
    context:
      button:
        text: More News
        type: bttn--outline bttn--tertiary bttn--sans-serif
        icon: yes
  - name: Button Outline Sans-Serif Background
    notes: This variation is used for the Hero Image component
    context:
      button:
        text: More News
        type: bttn--secondary bttn--sans-serif bttn--outline bttn--outline
        link: https://www.example.com
        icon:
  - name: Button Sans-Serif
    notes: This variation is used for Card Link component
    hidden: false
    context:
      button:
        text: More News
        type: bttn--link bttn--sans-serif
        icon: yes
