title: Footer
hidden: false
order: 40
meta:
  dependencies:
    stylesheets:
      - /components/prototype/logo/logo.css
      - /components/prototype/site-name/site-name.css
      - /components/prototype/parent-site-name/parent-site-name.css
context:
  footer_logo: ../../images/uiowa-secondary.svg#logo
  footer_type: uiowa
  contact_info: |
      <p>Iowa City, Iowa 52242<br>
          <a href="tel:319-335-3500"><i class="fas fa-phone"></i> 319-335-3500</a><br />
      </p>
  link_icon:
    items:
      - text: Facebook
        url: https://uiowa.edu/
        icon_class: fab fa-facebook-square
      - text:  Twitter
        url: https://uiowa.edu/
        icon_class: fab fa-twitter-square
      - text: Instagram
        url: https://uiowa.edu/
        icon_class: fab fa-instagram
      - text: Snapchat
        url: https://uiowa.edu/
        icon_class: fab fa-snapchat
      - text: Youtube
        url: https://uiowa.edu/
        icon_class: fab fa-youtube
      - text: LinkedIn
        url: https://uiowa.edu/
        icon_class: fab fa-linkedin
      - text: Pinterest
        url: https://uiowa.edu/
        icon_class: fab fa-pinterest
