title: IOWA Bar
context:
  site_name: Site Name
  site_name_position: inline
  parent_site:
    name: ''
    url: ''
variants:
  - name: default
    label: Just Logo
    context:
      site_name: ''
  - name: full
    label: Full
    context:
      iowa_bar_classes: 'iowa-bar--full'
  - name: narrow
    label: Narrow
    context:
      iowa_bar_classes: 'iowa-bar--narrow'
  - name: site_name_below
    label: Site name below
    context:
      site_name_position: below
  - name: parent_site_name
    label: Has parent site
    context:
      site_name: Brand Manual
      site_url: 'https://brand.uiowa.edu/'
      parent_site:
        name: Office of Strategic Communication
        url: 'https://osc.uiowa.edu/'