label: UIOWA Links
hidden: true
collated: false
order: 7
status: wip
context:
    bg_color: quick-links--primary
variants:
  - name: Black Background
    context:
      bg_color: quick-links--secondary
