title: Banner Block
order: 3
status: wip
context:
    banner_title: Bold Hawkeye Headline Here
    banner_summary: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
    banner_link_url: https://example.com
    banner_link_title: Call to Action
    banner_bg_image: ../../images/bg.jpg
    banner_image: ../../images/herky-01.png
