hidden: false
status: prototype
order: 0
meta:
  dependencies:
    stylesheets:
#      - /components/button/button.css
      - /components/headline/headline.css
context:
  backgrounds:
    - bg_name: 'Black - Brain pattern'
      bg_class: 'bg--black--pattern--brain'
    - bg_name: 'Black - Community Pattern'
      bg_class: 'bg--black--pattern--community'
    - bg_name: 'Black - Particle Pattern'
      bg_class: 'bg--black--pattern--particle'
    - bg_name: Black
      bg_class: 'bg--black'
    - bg_name: 'Gold - Brain pattern'
      bg_class: 'bg--gold--pattern--brain'
    - bg_name: 'Gold - Community Pattern'
      bg_class: 'bg--gold--pattern--community'
    - bg_name: 'Gold - Particle Pattern'
      bg_class: 'bg--gold--pattern--particle'
    - bg_name: Gold
      bg_class: 'bg--gold'
    - bg_name: 'Gray - Brain pattern'
      bg_class: 'bg--gray--pattern--brain'
    - bg_name: 'Gray - Community pattern'
      bg_class: 'bg--gray--pattern--community'
    - bg_name: 'Gray - Particle Pattern'
      bg_class: 'bg--gray--pattern--particle'
    - bg_name: Gray
      bg_class: 'bg--gray'
    - bg_name: 'White - Brain pattern'
      bg_class: 'bg--white--pattern--brain'
    - bg_name: 'White - Community pattern'
      bg_class: 'bg--white--pattern--community'
    - bg_name: 'White - Particle Pattern'
      bg_class: 'bg--white--pattern--particle'
    - bg_name: White
      bg_class: 'bg--white'
