title: Menu Group
hidden: false
order: 4
status: wip
context:
    menu_group_nav:
      title: Main Menu
      title_classes: element-invisible
      menu_classes: menu--group
      links:
      - menu_group_text: Alumni
        menu_group_classes:
      - menu_group_text: Athletics
        menu_group_classes: menuparent
      - menu_group_text: Health Care
        menu_group_classes: menuparent

variants:
  - name: default
    label: Menu Group Links
    hidden: false
    context:
       menu_classes: menu--group

  - name: reveresed
    label: Reversed Menu Group Links
    hidden: false
    context:
       menu_classes: menu--group menu--reversed

  - name: links
    label: Links
    hidden: true
