title: Highlighted Heading/Subheading
order: 2
status: wip
collated: false
hidden: false

variants:
  - name: default
    label: Headline
    hidden: false
    context:
      headline_level: h2
      highlight_title: Lorem ipsum dolor sit amet, consectetur
      highlight_sub: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi

