title: Quick Links
hidden: false
order: 4
status: wip
context:
    menu_quick_nav:
      title: Main Menu
      title_classes: element-invisible
      links:
      - menu_quick_text: MYUI
        menu_quick_classes:
        menu_quick_icon:
      - menu_quick_text: Jobs@UIowa
        menu_quick_classes: menuparent
        menu_quick_icon:
      - menu_quick_text: Human Resources
        menu_quick_classes: menuparent
        menu_quick_icon:
      - menu_quick_text: Student Health and Wellness
        menu_quick_classes: menuparent
        menu_quick_icon:
      - menu_quick_text: Libraries
        menu_quick_classes: menuparent
        menu_quick_icon:
      - menu_quick_text: Course Catalog
        menu_quick_classes: menuparent
        menu_quick_icon:
      - menu_quick_text: Academic Calendars
        menu_quick_classes: menuparent
        menu_quick_icon:

variants:
  - name: default
    label: Quick Links
    hidden: false

  - name: links
    label: Links
    hidden: true

  - name: search
    label: search
    hidden: true
    context:
      menu_quick_nav:
        title: Main Menu
        title_classes: element-invisible
        links:
        - menu_quick_text: A-Z Search
          menu_quick_classes: menuparent
          menu_quick_icon: far fa-bookmark
        - menu_quick_text: People Directory
          menu_quick_classes: menuparent
          menu_quick_icon: fas fa-user
