title: Feature Block
hidden: false
order: 3
status: wip
variants:
  - name: default
    label: Feature Block 3 Col
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature_slide3.jpg
            feature_link: https://example.com
  - name: Feature Block 2 Col
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
  - name: Feature Block 1 Col
    context:
      block_type: basic
      feature_type: image
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
  - name: Feature Block Video 3 Col
    context:
      block_type: advanced
      feature_type: video
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature_slide3.jpg
            feature_link: https://example.com
  - name: Feature Block Video 2 Col
    context:
      block_type: advanced
      feature_type: video
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
  - name: Feature Block Video 1 Col
    context:
      block_type: advanced
      feature_type: video
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
  - name: Feature Block Hover Collapsed
    context:
      block_type: basic
      feature_type:
      feature_state:
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature_slide3.jpg
            feature_link: https://example.com
  - name: Feature Block Accordion
    context:
      block_type: basic
      feature_type: image-stack
      feature_state: feature__container-expanded
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature_slide3.jpg
            feature_link: https://example.com
  - name: basic
    label: Feature Block Basic
    hidden: true
