title: Blockquote
status: wip
order: 30
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
      - /components/media/media.css
context:
      blockquote_content:  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      blockquote_footer: Footer Details in Roboto
      blockquote_cite_url: https://uiowa.edu/
      blockquote_cite_text: Link
      blockquote_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/events-01.jpg
      blockquote_image_position:

variants:
  - name: default
    label: Left (default)
    hidden: false
    context:
      blockquote_class: blockquote blockquote--left
  - name: Left borderless
    hidden: false
    context:
      blockquote_class: blockquote blockquote--left blockquote--borderless
  - name: Left with image aligned to the left of the content
    hidden: false
    context:
      blockquote_class: blockquote blockquote--left blockquote--img-above blockquote--borderless
      blockquote_image_position: blockquote--img-above
  - name: Left with image in footer
    hidden: false
    context:
      blockquote_class: blockquote  blockquote--left blockquote--img-below blockquote--borderless
      blockquote_image_position: blockquote--img-below
  - name: Center
    hidden: false
    context:
      blockquote_class: blockquote--center blockquote--borderless
      blockquote_image_position:
  - name: Center with image above
    hidden: false
    context:
      blockquote_class: blockquote--center blockquote--img-above blockquote--borderless
      blockquote_image_position: blockquote--img-above
  - name: Center with image in footer
    hidden: false
    context:
      blockquote_class: blockquote--center blockquote--img-below blockquote--borderless
      blockquote_image_position: blockquote--img-below
  - name: Right
    hidden: false
    context:
      blockquote_class: blockquote--right blockquote--borderless
  - name: Right with image to the right of the content
    hidden: false
    context:
      blockquote_class: blockquote--right blockquote--img-above blockquote--borderless
      blockquote_image_position: blockquote--img-above
  - name: Right with image in footer
    hidden: false
    context:
      blockquote_class: blockquote--right blockquote--img-below blockquote--borderless
      blockquote_image_position: blockquote--img-below
