hidden: true
status: prototype
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/card/card.css
      - /components/blockquote/blockquote.css
      - /components/media/media.css
      - /components/background/background.css
      - /components/colors/colors.css
      - /components/tables/tables.css
context:
  backgrounds: '@background.backgrounds'
  headlines: '@headline.headlines'
  cards:
    - card_title: Dedicated to having an impact on human health
      card_classes: card--stacked bg--white card--enclosed
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature1.jpg'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_subtitle: By Lee Hermiston
      card_aria: desc-a-card
    - card_title: Swinging for the fences in sports management
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature4.jpg'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_subtitle: By Lee Hermiston
      card_classes: card--enclosed card--stacked card--enclosed
      card_aria: desc-a-card
    - card_title: Turning the tide for sick seals
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature3.jpg'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_subtitle: By Sara Epstein Moninger
      card_classes: 'bg--gold card--stacked  card--enclosed'
      card_aria: desc-a-card
  horizontal_cards:
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--white card--media-left card--enclosed'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--black card--media-left card--enclosed'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--gray card--media-left card--enclosed'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote <a href="/">Text</a> More text </p> </blockquote><ul><li><a href="https://uiowa.edu">List item</a></li><li>List item</li></ul><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'
  buttons:
    - button_text: More News
      button_type: bttn--tertiary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
    - button_text: More News
      button_type: bttn--primary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
    - button_text: More News
      button_type: bttn--secondary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
    - button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--caps
      button_icon: yes
    - button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--sans-serif
      button_icon: yes
    - button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--transparent bttn--caps
      button_icon: yes
    - button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--transparent bttn--sans-serif
      button_icon: yes
    - button_text: More News
      button_type: bttn--link bttn--sans-serif
      button_icon: yes
