hidden: false
status: prototype
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/card/card.css
context:
  backgrounds: '@background.backgrounds'
  headlines: '@headline.headlines'
  cards: '@card--row.items'
