title: Headline
order: 10
status: wip
hidden: false
collated: true
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
context:
  backgrounds: "@background.backgrounds"
variants:
  - name: default
    label: Headline
    hidden: true
    context:
        headline_level: h2
        headline_class:
        headline_url:
        headline_prefix: '$'
        headline: 'Bold Headline Here'
        headline_suffix: '%'
        headline_aria: test
  - name: Headline Antonio with Underline
    hidden: false
    context:
      headline_level: h2
      headline: Headline Antonio Underline
      headline_class: bold-headline bold-headline--underline bold-headline--caps
  - name: Headline Caps
    hidden: false
    context:
      headline_level: h2
      headline: Headline Antonio
      headline_class: bold-headline bold-headline--caps
  - name: Headline Caps Single Word Highlight
    hidden: false
    context:
      headline_level: h2
      headline: Headline Antonio Single <span>Word</span> Highlighted
      headline_class: bold-headline bold-headline--caps
  - name: Headline Antonio with Highlight
    hidden: false
    context:
      headline_level: h2
      headline: Headline Antonio Highlighted
      headline_class: bold-headline bold-headline--caps bold-headline--highlight
  - name: Bold Headline Serif
    hidden: false
    context:
      headline_level: h2
      headline: Headline Zilla Slab
      headline_class: bold-headline bold-headline--serif
  - name: Headline Zilla with Underline
    hidden: false
    context:
      headline_level: h2
      headline: Headline Zilla Slab Underlined
      headline_class: bold-headline bold-headline--serif bold-headline--underline
  - name: Headline Zilla with Highlight
    hidden: false
    context:
      headline_level: h2
      headline: Headline Zilla Slab Highlighted
      headline_class: bold-headline bold-headline--serif bold-headline--highlight


