title: Site Name
label: Layouts
hidden: true
order: 10
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/branding/iowa-bar/iowa-bar.css
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/footer/footer.css
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
  feature_columns: feature__three-col
  feature_type: image
  feature:
    items:
      - feature_title: Having an Impact
        feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
        feature_banner_image: ../../images/feature_slide1.jpg
        feature_link: https://example.com
  icons:
    items:
      - icon_title: Areas of Study
        icon_link: https://example.com
        icon_image: ../../images/stack-of-books.svg#icon
      - icon_title: Cost and Aid
        icon_link: https://example.com
        icon_image: ../../images/scholarship.svg#icon
      - icon_title: Visit Campus
        icon_link: https://example.com
        icon_image: ../../images/map-pin.svg#icon
      - icon_title: Apply Now
        icon_link: https://example.com
        icon_image: ../../images/paper.svg#icon
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature1.jpg'
      - stat_title: '78%'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature2.jpg
      - stat_title: '14'
        stat_summary: 'consecutive years named a "Best Buy" by Fiske Guide to Colleges'
        stat_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature3.jpg
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature1.jpg'
  news:
    items:
      - news_card_tag: News
        news_card_title: Dedicated to having an impact on human health
        news_card_link_title: Read Article
        news_card_link_url: https://example.com
        news_card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature1.jpg
        news_card_text: Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.
        news_card_date: June 14, 1984
      - news_card_tag: News
        news_card_title: Getting to know Iowa's fall 2018 graduates
        news_card_link_title: Read Article
        news_card_link_url: https://example.com
        news_card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature2.jpg
        news_card_text: Receiving a diploma signals both an ending and a beginning.
        news_card_date: June 14, 1984
      - news_card_tag: News
        news_card_title: Turning the tide for sick seals
        news_card_link_title: Read Article
        news_card_link_url: https://example.com
        news_card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature3.jpg
        news_card_text: As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.
        news_card_date: June 14, 1984
      - news_card_tag: News
        news_card_title: Swinging for the fences in sports management
        news_card_link_title: Read Article
        news_card_link_url: https://example.com
        news_card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature4.jpg
        news_card_text: Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.
        news_card_date: June 14, 1984
  card:
    items:
      - card_tag: News
        card_title: Dedicated to having an impact on human health
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature1.jpg
        card_text: <p>Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
        card_date: June 14, 1984
      - card_tag: News
        card_title: Getting to know Iowa's fall 2018 graduates
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature2.jpg
        card_text: <p>Receiving a diploma signals both an ending and a beginning.</p>
        card_date: June 14, 1984
      - card_tag: News
        card_title: Turning the tide for sick seals
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature3.jpg
        card_text: <p>As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.</p>
        card_date: June 14, 1984
      - card_tag: News
        card_title: Swinging for the fences in sports management
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/feature4.jpg
        card_text: <p>Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.</p>
        card_date: June 14, 1984
  portrait:
    items:
      - portrait_title: Hannah Walsh
        portrait_sub: Business, 2019
        portrait_link: https://www.youtube.com/embed/0qYT5NpqN24?html5=1&enablejsapi=1&showinfo=0
      - portrait_title: Brady Campbell
        portrait_sub: Accounting, 2019
        portrait_link: https://www.youtube.com/embed/r8hLAfVz3sM?html5=1&enablejsapi=1
      - portrait_title: Molly Hammer
        portrait_sub: Psychology, 2019
        portrait_link: https://www.youtube.com/embed/jDMEv7HSSv4?html5=1&enablejsapi=1
  link_bttn:
    items:
    - link_bttn_title: Request Info
      link_bttn_url: https://example.com
      link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
      link_bttn_icon: fas fa-info-circle
    - link_bttn_title:  Visit
      link_bttn_url: https://example.com
      link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
      link_bttn_icon: fas fa-map-marker-alt
    - link_bttn_title: Apply
      link_bttn_url: https://example.com
      link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
      link_bttn_icon: fas fa-pencil-alt
    - link_bttn_title: Jobs
      link_bttn_url: https://example.com
      link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
      link_bttn_icon: fas fa-folder
  link_icon:
    items:
    - link_icon_title: Facebook
      link_icon_url: https://example.com
      link_icon_class: fab fa-facebook-square
    - link_icon_title:  Twitter
      link_icon_url: https://example.com
      link_icon_class: fab fa-twitter-square
      link_bttn_icon: fab fa-twitter-square
    - link_icon_title: Instagram
      link_icon_url: https://example.com
      link_icon_class: fab fa-instagram
    - link_icon_title: Snapchat
      link_icon_url: https://example.com
      link_icon_class: fab fa-snapchat
    - link_icon_title: Youtube
      link_icon_url: https://example.com
      link_icon_class: fab fa-youtube
  links_nav:
    links:
    - link_nav_text: Current section
      links:
      - link_nav_text: Navigation link 1
        link_nav_url: '#'
      - link_nav_text: Navigation link 2
        link_nav_url: '#'
      - link_nav_text: Navigation link 3
        link_nav_url: '#'
      - link_nav_text: Navigation link 4
        link_nav_url: '#'

variants:
  - name: default
    label: Default Secondary Superfish
    hidden: true
  - name: Default Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
      feature_columns: feature__two-col
      feature_type: image
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature_slide1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature_slide2.jpg
            feature_link: https://example.com
  - name: Default Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Left Secondary Superfish
    hidden: true
    context:
      site_slogan:
      header_alignment: site-header__left
      site_type: primary
      header_type: site-header--secondary
      nav_type: navbar--secondary
  - name: Aligned Left Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Left Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Center Secondary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: primary
  - name: Aligned Center Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Center Tertiary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Default Main Menu
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: main
      site_type: primary
  - name: Aligned Left Main Menu
    context:
      header_alignment: site-header__left
      menu_type: main
      site_type: primary
  - name: Aligned Center Main Menu
    hidden: true
    context:
      header_alignment: site-header__center
      menu_type: main
      site_type: primary
  - name: UIOWA Home Page Mega Menu
    hidden: true
    context:
      header_alignment: site-header__center
      menu_type: mega
      site_type: tertiary
      header_type:
      nav_type: navbar--tertiary


