title: Main Menu
hidden: false
order: 4
status: wip
context:
    field_title: Headline
    menu_type: main
    site_type: primary
variants:
  - name: Main Menu Secondary Horizontal
    hidden: false
    context:
      nav_type: main--secondary--horizontal
  - name: Main Menu Secondary Vertical
    hidden: false
    context:
      nav_type: main--secondary--vertical
