title: Viewbook
label: Viewbook
hidden: false
order: 10
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/branding/iowa-bar/iowa-bar.css
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/footer/footer.css
      - /components/typography/headings/headings.css
      - /components/typography/lists/lists.css
      - /components/typography/paragraph/paragraph.css
      - /components/tables/tables.css
      - /components/menus/top/top.css
      - /components/grid/grid.css
      - /components/menus/main-menu/main-menu.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/colors/colors.css
      - /components/viewbook/aerial/aerial.css
      - /components/cta/cta.css
      - /components/card/card.css
      - /components/stat/stat.css
      - /components/viewbook/grid-panel/grid-panel.css
      - /components/menus/vertical-dots/vertical-dots.css
    scripts:
      - /components/branding/iowa-bar/iowa-bar.js
      - /components/menus/off-canvas/off-canvas.js
      - /components/menus/vertical-dots/vertical-dots.js
      - /components/banner/banner.js
context:
  site_name:
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  iowa_bar_classes: 'iowa-bar--narrow'
  site_name_position: inline
  cta_title: 200+ Areas of Study
  cta_summary: Iowa offers over 200 majors, minors and certificates. Students are encouraged to work across disciplines to find their passion.
  cta_classes:
  cta_link_url: https://uiowa.edu/
  cta_link_title: Request Information
  cta_link_classes:
  banner_title_classes: 'bold-headline--caps bold-headline bold-headline--highlight'
  banner_vertical_alignment: banner--vertical-bottom
  banner_horizontal_alignment: banner--horizontal-left
  banner_text: ''
  banner_type: image
  banner_size: small
  banner_overlay: solid-opacity
  banner_aria: desc-a-card
  contact_info: |
      <p>Iowa City, Iowa 52242<br>
          <a href="tel:319-335-3847"><i class="fas fa-phone"></i> 319-335-3847</a><br />
      </p>
  banner_row:
    items:
      - banner_title: 'Business, economics, and management'
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/biz-econ-mgmt
        banner_image: '../../assets/images/viewbook/areas/1.jpg'
        banner_classes: banner--row
      - banner_classes: banner--row
        banner_title: Education
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/edu
        banner_image: '../../assets/images/viewbook/areas/2.jpg'
      - banner_title: Engineering and computing
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/engr-comp
        banner_image: '../../assets/images/viewbook/areas/3.jpg'
        banner_classes: banner--row
      - banner_title: Health sciences
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/health-sci
        banner_image: '../../assets/images/viewbook/areas/4.jpg'
        banner_classes: banner--row
      - banner_title: Languages, culture, and society
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/lang-cult-soc
        banner_image: '../../assets/images/viewbook/areas/5.jpg'
        banner_classes: banner--row
      - banner_title: Life and natural sciences
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/life-nat-sci
        banner_image: '../../assets/images/viewbook/areas/6.jpg'
        banner_classes: banner--row
      - banner_title: Math and quantitative sciences
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/math-quant-sci
        banner_image: '../../assets/images/viewbook/areas/7.jpg'
        banner_classes: banner--row
      - banner_title: Preprofessional programs
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/preprofessional
        banner_image: '../../assets/images/viewbook/areas/8.jpg'
        banner_classes: banner--row
      - banner_title: Social sciences and policy
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/soc-sci-pol
        banner_image: '../../assets/images/viewbook/areas/9.jpg'
        banner_classes: banner--row
      - banner_title: Visual and performing arts
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/vis-perf-arts
        banner_image: '../../assets/images/viewbook/areas/10.jpg'
        banner_classes: banner--row
      - banner_title: Writing, communications, literature, and media
        banner_links:
          - link_url: https://admissions.uiowa.edu/academics/write-comm-media
        banner_image: '../../assets/images/viewbook/areas/11.jpg'
        banner_classes: banner--row
      - banner_links:
          - link_title: Browse by Major
            link_url: https://admissions.uiowa.edu/academics/undergraduate-areas-of-study
        banner_type:
        banner_vertical_alignment: banner--vertical-center
        banner_horizontal_alignment: banner--horizontal-left
        banner_overlay:
        banner_classes: banner--row bg-pattern--brain-black
        banner_link_classes: bttn bttn--secondary bttn--caps
  link_bttn:
    items:
      - text: Apply Now
        url: https://admissions.uiowa.edu/apply/first-year-student-application-process
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--apply
      - text:  Schedule a Visit
        url: https://admissions.uiowa.edu/visit-campus
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--visit
      - text: Contact Us
        url: https://admissions.uiowa.edu/contact-us
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--ask
      - text: Request Information
        url: https://www.maui.uiowa.edu/maui/pub/admissions/webinquiry/undergraduate.page
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--connect
  stat_row_1:
    items:
      - stat_title: '34'
        stat_summary: 'BEST PUBLIC UNIVERSITY BY U.S. NEWS & WORLD REPORT'
        stat_content: 'Among the top 2% of universities worldwide.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: '#'
        stat_suffix:
        stat_classes: 'stat--horizontal'
      - stat_title: '15:1'
        stat_summary: 'STUDENT-TO-FACULTY<br /> RATIO'
        stat_content: 'Get to know your professors.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: ''
        stat_classes: 'stat--horizontal'
      - stat_title: '23'
        stat_summary: 'INTERNATIONAL FULBRIGHT<br />  SCHOLARS IN 2020'
        stat_content: 'That’s the same as some Ivy League schools.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix:
        stat_classes: 'stat--horizontal'
      - stat_title: '1 in 3'
        stat_summary: 'UNDERGRADS PARTICIPATE IN RESEARCH'
        stat_content: 'Gain experience now.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix:
        stat_classes: 'stat--horizontal'
  stat_row_2:
    items:
      - stat_title: '500'
        stat_summary: 'STUDENT<br />  ORGANIZATIONS'
        stat_content: 'Or, start your own.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
      - stat_title: '100'
        stat_summary: 'RESTAURANTS AND<br />  CAFÉS'
        stat_content: 'From vegan brunch to pie shakes.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
      - stat_title: '400'
        stat_summary: 'ARTS PERFORMANCES Available EACH YEAR'
        stat_content: 'For $5 or less.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
      - stat_title: '24'
        stat_summary: 'NCAA DIVISION I<br />  TEAMS'
        stat_content: 'There’s nothing like a Hawkeye game.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix:
        stat_classes: 'stat--horizontal'
  stat_row_3:
    items:
      - stat_title: '95'
        stat_summary: 'OVERALL JOB/GRADUATE SCHOOL PLACEMENT RATE'
        stat_content: 'Business <strong>97%</strong><br />Education <strong>91%</strong><br />Engineering  <strong>96%</strong><br /> Liberal Arts and Sciences <strong>94%</strong><br /> Nursing <strong>99%</strong><br />Pharmacy <strong>97%</strong>'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '%'
        stat_classes: 'stat--horizontal'
      - stat_title: '4,000'
        stat_summary: 'STUDENT<br />  INTERNSHIPS'
        stat_content: 'Everywhere from NASA to the Minnesota Vikings.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
      - stat_title: '4,100'
        stat_summary: 'Employers have hired Iowa Graduates the past three years'
        stat_content: 'Gain real-world skills that make résumés stand out.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
      - stat_title: '1,316'
        stat_summary: 'STUDENTS STUDIED ABROAD LAST YEAR'
        stat_content: 'Spanning the globe in 69 countries.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '+'
        stat_classes: 'stat--horizontal'
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
  vertical_dots:
    sections:
      - section_title: "Back to Top"
        section_id: "banner-banner"
      - section_title: "Areas of Study"
        section_id: "areas-of-study"
      - section_title: "Acdemic Opportunities"
        section_id: "academic-opportunities"
      - section_title: "Iowa City"
        section_id: "iowa-city"
      - section_title: "Student Life"
        section_id: "student-life"
      - section_title: "Student Outcomes"
        section_id: "student-outcomes"
      - section_title: "How to Apply"
        section_id: "apply"
  link_icon:
    items:
      - text: Facebook
        url: http://www.facebook.com/admissions.office
        icon_class: fab fa-facebook-square
      - text: Instagram
        url: http://instagram.com/iowaadmissions
        icon_class: fab fa-instagram
      - text:  Twitter
        url: https://twitter.com/iowaadmissions
        icon_class: fab fa-twitter-square
      - text: Youtube
        url: http://www.youtube.com/uiowaadmissions
        icon_class: fab fa-youtube
  grid_panel_1:
    items:
      - grid_type: asymmetrical
        grid_content_position: first
        grid_panel_first_column : grid-panel__column-content-left grid-panel__content
        grid_panel_second_column : grid-panel__column-image-right
        grid_panel_image:
        grid_panel_content: '<p>Iowa offers over 200 majors, minors and certificates. Students are encouraged to work across disciplines to find their passion. If you are unsure of what you’d like to study at Iowa, look at an&nbsp;<a data-cke-saved-href="https://admissions.uiowa.edu/academics/open-major" href="https://admissions.uiowa.edu/academics/open-major">open major</a>, or take our&nbsp;<a data-cke-saved-href="http://uiowa.mymajors.com/" href="http://uiowa.mymajors.com/">MyMajors assessment</a>&nbsp;to explore possible majors based on your interests and strengths.</p>'
        grid_panel_headline: '200+ Areas<br /> of Study'
        button:
          text: View Areas of Study
          type: bttn bttn--secondary bttn--caps
          link: https://admissions.uiowa.edu/academics/undergraduate-areas-of-study
          icon: yes
  grid_panel_2:
    items:
      - grid_type: asymmetrical
        grid_content_position: second
        grid_panel_first_column : grid-panel__column-image-left
        grid_panel_second_column : grid-panel__column-content-right grid-panel__content
        grid_panel_image: '<img class="grid-panel__img" src="../../assets/images/viewbook/sections/0315.jpg" alt="Alt Text" />'
        grid_panel_content: '<p>The University of Iowa blends big-school opportunities with close, personal support to help you excel. We remove the barriers between arts and science, between students and faculty—but most of all, between you and anything you’d like to explore.</p>
    <p>How many universities have both a state-of-the-art children’s hospital and
      a 3,883-pipe Klais organ? Or helped build the Voyager I satellite and the very first creative writing degree program? Just one: Iowa.</p>'
        grid_panel_headline: 'We Work <span>Together</span>'
        button:
          text: View Academic Opportunities
          type: bttn bttn--secondary bttn--caps
          link: https://admissions.uiowa.edu/academics/academics
          icon: yes
  grid_panel_3:
    items:
      - grid_type: asymmetrical
        grid_content_position: first
        grid_panel_first_column : grid-panel__column-content-left grid-panel__content
        grid_panel_second_column : grid-panel__column-image-right
        grid_panel_image: '<img class="grid-panel__img" src="../../assets/images/viewbook/sections/1304.jpg" alt="Alt Text" />'
        grid_panel_content: '<p>Big Ten athletics, theaters, music venues, 500+ student groups, community organizations, student philanthropy, hiking trails, bike paths, workout facilities, hundreds of restaurants and coffee shops and food carts and—you get the idea. There’s a lot to do in Iowa City. Every club, event, and activity is an opportunity to make new connections and find your own close-knit community on campus.</p>'
        grid_panel_headline: 'Make <span>30,000</span> New Friends'
        button:
          text: View Student Life
          type: bttn bttn--secondary bttn--caps
          link: https://admissions.uiowa.edu/student-life/student-life
          icon: yes
  grid_panel_4:
    items:
      - grid_type: asymmetrical
        grid_content_position: second
        grid_panel_first_column : grid-panel__column-image-left
        grid_panel_second_column : grid-panel__column-content-right grid-panel__content
        grid_panel_image: '<img class="grid-panel__img" src="../../assets/images/viewbook/sections/1961.jpg" alt="Alt Text" />'
        grid_panel_content: '<p>Having big ideas isn’t enough—to excel in any career, you need to know how to share them and make them real. Iowa’s leadership in the study and craft of writing helps every Hawkeye learn communication skills that give them an edge. Dedicated career advising, thousands of on-campus job interviews, and countless opportunities for hands-on learning make Iowa grads stand out.</p>'
        grid_panel_headline: 'Make an <span>Impact</span>'
        button:
          text: View Student Outcomes
          type: bttn bttn--secondary bttn--caps
          link: https://stories.uiowa.edu/student-outcomes
          icon: yes
  grid_panel_5:
    items:
      - grid_type: split
        grid_content_position: first
        grid_panel_first_column : grid-panel__column grid-panel__content
        grid_panel_second_column : grid-panel__column grid-panel__content
        grid_panel_image:
        grid_panel_content:
        grid_panel_headline: 'How to Apply'
        button:
          text:
          type:
          link:
          icon:


