title: Footer
hidden: true
order: 9
status: wip
context:
  footer_logo: ../../images/uiowa-secondary.svg#logo
  footer_type: uiowa
  contact_info: |
      <p>Iowa City, Iowa 52242<br>
          <a href="tel:319-335-3500"><i class="fas fa-phone"></i> 319-335-3500</a><br />
          <a href="/contact"><i class="fas fa-envelope"></i> Contact Us</a>
      </p>
  link_bttn:
    items:
      - text: Apply
        url: https://uiowa.edu/
        class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--apply
#        icon_class: fas fa-info-circle
      - text:  Visit
        url: https://uiowa.edu/
        class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--visit
#        icon_class: fas fa-map-marker-alt
      - text: Request Info
        url: https://uiowa.edu/
        class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--request
#        icon_class: fas fa-pencil-alt
      - text: Jobs
        url: https://uiowa.edu/
        class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--jobs
#        icon_class: fas fa-folder
  link_icon:
    items:
      - text: Facebook
        url: https://uiowa.edu/
        icon_class: fab fa-facebook-square
      - text:  Twitter
        url: https://uiowa.edu/
        icon_class: fab fa-twitter-square
      - text: Instagram
        url: https://uiowa.edu/
        icon_class: fab fa-instagram
      - text: Snapchat
        url: https://uiowa.edu/
        icon_class: fab fa-snapchat
      - text: Youtube
        url: https://uiowa.edu/
        icon_class: fab fa-youtube
      - text: LinkedIn
        url: https://uiowa.edu/
        icon_class: fab fa-linkedin
      - text: Pinterest
        url: https://uiowa.edu/
        icon_class: fab fa-pinterest
  links_nav_1:
    items:
      - text: About Iowa
        url: '#'
      - text: MyUI
        url: '#'
      - text: Jobs@Iowa
        url: '#'
      - text: Human resources
        url: '#'
      - text: Student health
        url: '#'
      - text: Libraries
        url: '#'
      - text: Course catalog
        url: '#'
      - text: Academic calendars
  links_nav_2:
    items:
      - text: Emergency Info
        url: '#'
      - text: Campus Safety
        url: '#'
      - text: Maps
        url: '#'
      - text: Directory
        url: '#'
      - text: A-Z Search
        url: '#'
  links_nav_3:
    items:
      - text: Privacy
        url: '#'
      - text: Accessibility
        url: '#'
      - text: Nondiscrimination
        url: '#'
      - text: Contact
        url: '#'

variants:
  - name: default
    label: Home Page
    hidden: false
  - name: College
    label: College
    hidden: false
    context:
      site_name: College of Law
      site_slogan:
      footer_type: department
      contact_info: |
        <p>280 Boyd Law Building<br/>
            Melrose & Byington<br/>

            ​Iowa City, IA 52242<br/>

            <a href="tel:319-335-3500">319-335-9034</a><br/>

            <a href="mailto:law-webmaster@uiowa.edu">law-webmaster@uiowa.edu</a>
        </p>
  - name: Department
    label: Department
    hidden: false
    context:
      site_name: College of Law
      site_slogan: Department of Admissions
      footer_type: department
      contact_info: |
        <p>280 Boyd Law Building<br/>
            Melrose & Byington<br/>

            ​Iowa City, IA 52242<br/>

            <a href="tel:319-335-3500">319-335-9034</a><br/>

            <a href="mailto:law-webmaster@uiowa.edu">law-webmaster@uiowa.edu</a>
        </p>
  - name: contact-info
    label: Footer Contact Info
    hidden: true
  - name: links-bttn
    label: Footer Links Bttn
    hidden: true
  - name: socket-menu
    label: Footer Socket Menu
    hidden: true
