title: Headers
hidden: false
order: 10
status: wip

variants:
  - name: default
    label: Home Page
    hidden: false
    context:
      site_name: site name
      site_slogan: slogan
      site_title:
      header_nav: header--toggle
      header_type: header--primary
      header_action: header--sticky
  - name: Site Name with off-canvas
    label: College
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan: slogan
      site_title:
      header_nav: header--toggle
      header_type: header--secondary
      header_action: header--sticky
  - name: site-subnav
    label: Site Name with Subnav
    hidden: false
    context:
      site_name: Carver College of Medicine
      site_slogan:
      site_title:
      header_nav: header--horizontal
      header_type: header--secondary
      header_action:
  - name: Department Nav with off-canvas
    label: Department
    hidden: false
    context:
      site_name: Iowa Consortium Substance Abuse Research and Evaluation
      site_slogan: Carver College of Medicine
      site_title:
      header_nav: header--toggle
      header_type: header--tertiary
      header_action: header--sticky
  - name: Department Nav
    label: Department w/nav
    hidden: false
    context:
      site_name: Fraternal Order of Eagles Diabetes Research Center
      site_slogan: Carver College of Medicine
      site_title:
      header_nav: header--horizontal
      header_type: header--tertiary
