title: Banner
order: 3
status: wip
hidden: false
meta:
  dependencies:
    stylesheets:
      - /components/button/button.css
      - /components/headline/headline.css
context:
  banner_title: 200+ Areas of Study
  banner_summary: When it comes to your academic path, weâ€™re flexible. You can work across disciplines and add new areas of focus as you go.
  banner_link_url: https://example.com
  banner_link_title: View Majors
  banner_bg_image: ../../images/bg.jpg
  banner_image: ../../images/herky-01.png
  bttn_class: bttn bttn--primary bttn--caps
  image_path_1: ../../images/widescreen__384_x_216/bg-image.jpg
  image_path_2: ../../images/widescreen__768_x_432/bg-image.jpg
  image_path_3: ../../images/widescreen__1024_x_576/bg-image.jpg
  image_path_4: ../../images/widescreen__1312_x_738/bg-image.jpg
  image_path_5: ../../images/widescreen__1920_x_1080/bg-image.jpg
  image_path_6: ../../images/widescreen__2592_x_1458/bg-image.jpg
variants:
  - name: default
  - name: reversed
    label: Reversed
    context:
      banner_classes: 'banner--reversed'
