title: Slider
hidden: false
order: 40
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
variants:
  - name: default
    label: 3 Slides
    hidden: false
    context:
      slides:
        - slide_title: Having an Impact
          slide_sub: <p>Jordan Kohlmeyer is researching new therapies for tumors</p>
          slide_banner_image: '../../../assets/images/examples/feature1.jpg'
          slide_banner_class: banner--reversed
          slide_expanded: true
        - slide_title: 2019 Graduates
          slide_sub: <p>Receiving a diploma signals both an ending and a beginning</p>
          slide_banner_image: '../../../assets/images/examples/feature2.jpg'
          slide_banner_class: banner--reversed
        - slide_title: Turning the Tide
          slide_sub: <p>Alumna Lauren Palmer aims to rehabilitate animals</p>
          slide_banner_image: '../../../assets/images/examples/feature3.jpg'
          slide_link: https://example3.com
          slide_link_title: Read More
          slide_link_class: bttn bttn--primary bttn--caps
          slide_banner_class: banner--reversed
  - name: 2_slides
    label: 2 Slides
    hidden: false
    context:
      slides:
        - slide_title: Having an Impact
          slide_sub: <p>Jordan Kohlmeyer is researching new therapies for tumors</p>
          slide_banner_image: '../../../assets/images/examples/feature1.jpg'
          slide_link: https://example.com
          slide_link_title: Read More
          slide_link_class: bttn bttn--primary bttn--caps
          slide_banner_class: banner--reversed
          slide_expanded: true
        - slide_title: 2019 Graduates
          slide_sub: <p>Receiving a diploma signals both an ending and a beginning</p>
          slide_banner_image: '../../../assets/images/examples/feature2.jpg'
          slide_link: https://example.com
          slide_link_title: Read More
          slide_link_class: bttn bttn--primary bttn--caps
          slide_banner_class: banner--reversed
  - name: 1_slide
    label: Fallback
    context:
      slides:
        - slide_title: Having an Impact
          slide_sub: Jordan Kohlmeyer is researching new therapies for tumors
          slide_banner_image: '../../../assets/images/examples/feature3.jpg'
          slide_link: https://example.com
          slide_link_title: Read More
          slide_link_class: bttn bttn--primary bttn--caps
          slide_banner_class: banner--reversed
          slide_expanded: true
  - name: multiple
    label: Multiple
    context:
      slides:
        - slide_title: Having an Impact
          slide_sub: Jordan Kohlmeyer is researching new therapies for tumors
          slide_banner_image: '../../../assets/images/examples/feature1.jpg'
          slide_banner_class: banner--reversed
          slide_expanded: true
        - slide_title: 2019 Graduates
          slide_sub: Receiving a diploma signals both an ending and a beginning
          slide_banner_image: '../../../assets/images/examples/feature2.jpg'
          slide_banner_class: banner--reversed
        - slide_title: Turning the Tide
          slide_sub: Alumna Lauren Palmer aims to rehabilitate animals
          slide_banner_image: '../../../assets/images/examples/feature3.jpg'
          slide_link: https://example3.com
          slide_link_title: Read More
          slide_link_class: bttn bttn--primary bttn--caps
          slide_banner_class: banner--reversed
  - name: slide
    hidden: true
