hidden: false
status: prototype
order: 0
meta:
  dependencies:
    stylesheets:
#      - /components/button/button.css
      - /components/headline/headline.css
context:
  backgrounds:
    - bg_name: Black
      bg_class: 'bg--black'
    - bg_name: Gold
      bg_class: 'bg--gold'
    - bg_name: Gray
      bg_class: 'bg--gray'
    - bg_name: 'Brain pattern - Black'
      bg_class: 'bg-pattern--brain--black'
    - bg_name: 'Brain pattern - Gold'
      bg_class: 'bg-pattern--brain--gold'
    - bg_name: 'Brain pattern - White'
      bg_class: 'bg-pattern--brain'
